
version: "3.9"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8088:8080"

  eureka-server:
    build: ./eureka-server
    ports: ["8761:8761"]

  config-server:
    build: ./config-server
    ports: ["8888:8888"]
    depends_on: [eureka-server]

  api-gateway:
    build: ./api-gateway
    ports: ["8080:8080"]
    depends_on: [eureka-server, keycloak]

  product-service:
    build: ./product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports: ["8081:8081"]
    depends_on: [postgres, eureka-server, keycloak]

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: produser
      POSTGRES_PASSWORD: prodpass
    ports: ["5432:5432"]

  # elk stack omitted for brevity
