spring:
  profiles: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/demo-realm

  eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
