spring:
  profiles: dev

  security:
    oauth2.resourceserver.jwt.issuer-uri: ${SECURITY_OAUTH2_ISSUER_URI}

  cloud.gateway.discovery.locator.enabled: true
  eureka.client.service-url.defaultZone: ${EUREKA_URL}

  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASS}

server.port: ${SERVER_PORT:8080}
