spring:
  profiles: test

  eureka.client.enabled: false      # registry not needed in unit tests

  security.oauth2.resourceserver.jwt.issuer-uri: ${SECURITY_OAUTH2_ISSUER_URI}

  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASS}

server.port: 0   # random free port
logging.level.root: WARN
