spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery.locator.enabled: ${DISCOVERY_ENABLED:true}
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_OAUTH2_ISSUER_URI:}   # override per-profile

  # Optional: if you ever add DB or Redis to the gateway
  datasource:
    url: ${JDBC_URL:}
    username: ${JDBC_USER:}
    password: ${JDBC_PASS:}

server:
  port: ${SERVER_PORT:8080}

logging:
  level.root: INFO
