spring:
  profiles: local

server.port: 8761

eureka:
  client:
    register-with-eureka: false      # standalone
    fetch-registry: false
    service-url.defaultZone: http://localhost:8761/eureka
  instance.hostname: localhost
