spring:
  profiles: dev

server.port: 8761

eureka:
  client:
    register-with-eureka: false      # self-hosted registry
    fetch-registry: false
    service-url.defaultZone: http://eureka-server:8761/eureka
  instance.hostname: eureka-server
