spring.application.name: eureka-server

server.port: ${SERVER_PORT:8761}

eureka:
  instance.hostname: ${EUREKA_HOSTNAME:${HOSTNAME:localhost}}
  client:
    # Let profile files decide register/fetch
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}
