# Development environment configuration
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:tenant_registry}
    username: ${DB_USERNAME:?}
    password: ${DB_PASSWORD:?}
  liquibase:
    contexts: dev

# Keycloak configuration for development
keycloak:
  server-url: ${KEYCLOAK_URL:?}
  admin-username: ${KC_ADMIN_USERNAME:?}
  admin-password: ${KC_ADMIN_PASSWORD:?}
  default-client-secret: ${KC_CLIENT_SECRET:?}

# Logging configuration for development
logging:
  level:
    com.example: INFO
    org.springframework.security: INFO