# Production environment configuration
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:?}:${DB_PORT:5432}/${DB_NAME:?}
    username: ${DB_USERNAME:?}
    password: ${DB_PASSWORD:?}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  liquibase:
    contexts: prod
  jpa:
    properties:
      hibernate:
        format_sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:?}/realms/${KEYCLOAK_REALM:?}

# Server configuration for production
server:
  tomcat:
    max-threads: 200
    min-spare-threads: 20
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048

# Keycloak configuration for production
keycloak:
  server-url: ${KEYCLOAK_URL:?}
  admin-username: ${KC_ADMIN_USERNAME:?}
  admin-password: ${KC_ADMIN_PASSWORD:?}
  default-client-secret: ${KC_CLIENT_SECRET:?}

# Actuator configuration for production
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never

# Logging configuration for production
logging:
  level:
    root: WARN
    com.example: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/tenant-registry-svc.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7