# Local development configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tenant_registry
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    contexts: local

# Keycloak configuration for local development
keycloak:
  server-url: http://localhost:8080
  admin-username: admin
  admin-password: admin
  default-client-secret: secret

# Logging configuration for local development
logging:
  level:
    com.example: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE