spring:
  profiles: prod

  cloud.config.server:
    git:
      uri: ${CONFIG_REPO_URI}          # e.g. https://github.com/acme/configs
      username: ${CONFIG_REPO_USER}
      password: ${CONFIG_REPO_PASS}
      default-label: main

eureka.client.service-url.defaultZone: ${EUREKA_URL}
server.port: ${SERVER_PORT:8888}

management.endpoints.web.exposure.include: health,info
