name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: products
          POSTGRES_USER: produser
          POSTGRES_PASSWORD: prodpass
        ports: [5433:5432]
        options: >-
          --health-cmd "pg_isready -U produser" --health-interval 10s
          --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Build Spring modules
        run: mvn -B -pl eureka-server,config-server,api-gateway,product-service -am verify
      - name: Build Next.js
        run: |
          cd nextjs-frontend
          npm ci
          npm run build
